#!/bin/sh
_keyfile_process(){
	case "$1" in
	"!starting")
		echo "_keyfile_before";;
	"!ending")
		echo "_keyfile_ending";;
	*)
		echo "_keyfile_main";;
	esac
}

_keyfile_before(){
	echo "" > /dev/null
}
_keyfile_main(){
		local title=$(printf "%s" "${line}" | awk '{print $1}' FS="${key_delimiter}")  #";")
 		local otherchars=$(printf "%s" "${line}" | awk '{print $2}' FS="${key_delimiter}")   #";")
		local key=$(printf "%s" "${line}" | awk '{print $3}' FS="${key_delimiter}") #";")
		local sizeing=$(printf "%s" "${line}" | awk '{print $4}' FS="${key_delimiter}")  #";")

                printf "%s\n" "        { ${title}, ${otherchars}, ${key}, ${sizeing} }, " >>  $key_OF
}
_keyfile_ending(){
	{ echo ""; echo  "        { 0 }, /* New row */";echo ""; } >> $key_OF
}
